AOM-26: UI improvements and fix location drop down bug
openmrs/openmrs-owa-addonmanager pull request #33
Opened 2017-09-22 14:04 UTC by andela-jomadoye

# JIRA TICKET NAME:
AOM-22: [UI improvements and fix location drop down bug](https://issues.openmrs.org/browse/AOM-26)

## SUMMARY:
This PR ensures that the current location is displayed to the user on the dropdown, as well as other slight UI fixes

2017-09-22 14:14 UTC, kingisaac95 commented on app/js/components/common/header.js
>                {/*Execute the function*/}
I don't think this comment is necessary here

2017-09-22 14:16 UTC, kingisaac95 commented on app/js/components/common/header.js
> +              <span className="glyphicon glyphicon-log-out navbar-glyphicon-font"/></a>
Could you bring the closing `</a>` tag to a new line to match the opening tag?

2017-09-22 14:19 UTC, kingisaac95 commented on app/css/openmrs-addonmanager.css
> +    margin-top: 5px !important;
Can we not have `!important` @andela-jomadoye?

2017-09-22 14:21 UTC, kingisaac95 requested changes

2017-09-22 14:21 UTC, kingisaac95 commented on app/css/openmrs-addonmanager.css
> +     background-color: #5B57A6 !important;
Ditto

2017-09-22 14:22 UTC, kingisaac95 commented
Nice job @andela-jomadoye!! 👍

2017-09-25 09:57 UTC, wanjikum commented
Looks good 👍

2017-09-25 09:59 UTC, paulupendo commented
Good Job @andela-jomadoye

2017-09-26 11:37 UTC, merged